---
author: DixieCyanide
main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
api-version: '1.13'
depend:
  - FastAsyncWorldEdit
softdepend:
  - SchematicBrush
commands:
  /wood:
    description: Creates a forest/wood in your selection from schematics
    usage: //wood {schematic(s)} [!]{block ID(s)} [flags -includeAir,-dontRotate,-r:x]
    aliases:
      - /wood
      - /w
    permission: btemoreenhanced.region.wood
  btemoreenhanced-reload:
    description: Reload config
    usage: /btemoreenhanced-reload
    permission: btemoreenhanced.reload
  /treebrush:
    description: Easy to use brush specifically for trees on top of //schbr (Schematic Brush Plugin)
    usage: //treebrush {type} [size] [thickness]
    aliases:
      - /tbr
      - /treebr
      - /treebrush
  /dell:
    description: Deletes last [num] point(s) in poly2d or convex selection
    usage: //dell [num]
    aliases:
      - /dell
      - /dellast
    permission: btemoreenhanced.selection.dellast
  /delf:
    description: Deletes first [num] point(s) in poly2d or convex selection
    usage: //delf [num]
    aliases:
      - /delf
      - /delfirst
    permission: btemoreenhanced.selection.delfirst
  /delp:
    description: Deletes the [num] point in poly2d or convex selection
    usage: //delp [num]
    aliases:
      - /delp
      - /delpoint
    permission: btemoreenhanced.selection.delpoint
  /terraform:
    description: Makes platform of emeralds on specified {height} and clears below([delbot]) and above([deltop])
    usage: //terraform {height} [delbot] [deltop]
    aliases:
      - /terraform
      - /terr
      - /tf
    permission: btemoreenhanced.region.terraform
  /reach:
    description: Changes interaction distance {length} with blocks and entities.
    usage: //reach {length}
    aliases:
      - /reach
    permission: bteemoreenhanced.player.reach
  /bmesettings:
    description: Shows personal plugin settings
    usage:  //bmesettings
    aliases:
      - /bmesetting
      - /settings
permissions:
  btemoreenhanced.*:
    description: Wildcard permission
    children:
      btemoreenhanced.region: true
      btemoreenhanced.region.wood: true
      btemoreenhanced.region.terraform: true
      btemoreenhanced.reload: true
      btemoreenhanced.selection: true
      btemoreenhanced.selection.dellast: true
      btemoreenhanced.selection.delfirst: true
      btemoreenhanced.selection.delpoint: true
      btemoreenhanced.player.reach: true
      btemoreenhanced.player.settings: true
  btemoreenhanced.admin.*:
    description: All "admin" perms
    children:
      btemoreenhanced.admin.reload: true
      btemoreenhanced.admin.allschematics: true
  btemoreenhanced.admin.reload:
    description: Reload config
  btemoreenhanced.admin.allschematics:
    description: Allows people to use all files in schematics folder
  btemoreenhanced.region.*:
    description: All region commands
    children:
      btemoreenhanced.region.wood: true
      btemoreenhanced.region.terraform: true
  btemoreenhanced.region.wood:
    description: Allows usage of //wood
  btemoreenhanced.region.terraform:
    description: Allows usage of // terraform
  btemoreenhanced.selection.*:
    description: Allows usage of all selection related commands
    children:
      btemoreenhanced.selection.dellast: true
      btemoreenhanced.selection.delfirst: true
      btemoreenhanced.selection.delpoint: true
  btemoreenhanced.selection.dellast:
    description: Allows usage of //dell
  btemoreenhanced.selection.delfirst:
    description: Allows usage of //delf
  btemoreenhanced.selection.delpoint:
    description: Allows usage of //delp
  btemoreenhanced.player.*:
    description: All commands affecting players
    children:
      btemoreenhanced.player.reach: true
      btemoreenhanced.player.settings: true
  btemoreenhanced.player.reach:
    description: Allows usage of //reach
  btemoreenhanced.player.settings:
    description: Allows usage of //bmesettings
